Number of train_response logs 58926
[Epoch 1]
Training:   0%|‚ñè                                                    | 1/231 [00:00<00:44,  5.15it/s]
Traceback (most recent call last):
  File "d:\Git\IDCDF-WKY\run.py", line 65, in <module>
    sys.exit(main(config_dict))
             ^^^^^^^^^^^^^^^^^
  File "d:\Git\IDCDF-WKY\run.py", line 62, in main
    idcdm.train(datahub, "train", "valid", valid_metrics=validate_metrics, batch_size=config['batch_size'],epoch=config['epoch'], lr=config['lr'])
  File "d:\Git\IDCDF-WKY\inscd\models\idcdm.py", line 45, in train
    self._train(datahub=datahub, set_type=set_type,
  File "d:\Git\IDCDF-WKY\inscd\_base.py", line 50, in _train
    unifier.train(datahub, set_type, self.extractor, self.inter_func, **kwargs)
  File "d:\Git\IDCDF-WKY\inscd\_unifier.py", line 47, in train
    loss.backward()
  File "C:\Users\admin.DESKTOP-7USASVH\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\_tensor.py", line 525, in backward
    torch.autograd.backward(
  File "C:\Users\admin.DESKTOP-7USASVH\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\autograd\__init__.py", line 267, in backward
    _engine_run_backward(
  File "C:\Users\admin.DESKTOP-7USASVH\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\autograd\graph.py", line 744, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.
